### ISSUE TITLE
Support `info variables`-like command.

### ISSUE THREAD

**Issue by panzhongxian** [mostafa/goja#11]
Some debugger like gdb has command `info variables` to list "All global and static variable names". Or using `info locals` to list "Local variables of current stack frame".

If integerated with IDE like VS Code, there is window to show both locals and globals.

I know we can print single variable by invoking `print` command, which is implemented by calling `getValue()`. This function looks up variables from nested stashes and global object. I found even if I defined a local variable with `let`, the value would be found in global object finally.

Do you have any plan to add these commands? Or can you give me any advice on how to implement this?

**Comment by mostafa** [comment]
This one is really tricky, as we don't have access to the local variable, until we're inside the functions or blocks. Also, it was impossible to address function parameters inside a function as variables, as some optimization in Goja would prevent it. I think it's fixed now, but it should be double-checked.
Anyhow, this is a really good thing to add.

**Comment by panzhongxian** [comment]
Closed by #18 temporarily.
