### ISSUE TITLE
Remove the second time stop on the parent function.

### ISSUE THREAD

**Issue by panzhongxian** [mostafa/goja#9]
Consider the case, we set two breakpoints as following:

```javascript
function HelloDebugger() {
  var o = {     // <--- set breakpoint here
    a : 123,
    b : 666
  };
}

function AAA() { return HelloDebugger(); }

function BBB() {
  return AAA(); // <--- set breakpoint here
}

BBB();
```

Currently, we will break on `return AAA();` for second time after we break inside `HelloDebugger()`.

This seems OK if we run the in the plain code.

Consider the `for`-loop, this behavior will confuse users.

@mostafa

**Comment by panzhongxian** [comment]
@mostafa 

Try the code:

```javascript
debugger

function HelloDebugger() {
  // <--- set breakpoint on next line
  var o = {a : 123, b : 666};
}

function AAA() { return HelloDebugger(); }

function BBB() {
  return AAA(); // <--- set breakpoint here
}

BBB();

//# sourceMappingURL=test.js.map
```

And you will get the result:

```diff
Welcome to Goja debugger
Type 'help' or 'h' for list of commands.
Loaded sourcemap from: scripts/test.js.map
Break on debugger statement in scripts/test.js:14
debug[5]> sb scripts/test.js 14
debug[5]> sb scripts/test.js 5
debug[5]> c
Break on breakpoint in scripts/test.js:14
sdebug[5]> c
Break on breakpoint in scripts/test.js:5
sdebug[2]> c
Break on breakpoint in scripts/test.js:14
sdebug[7]> c
```

**Comment by mostafa** [comment]
Well done! 👏

**Comment by mostafa** [comment]
Can you add it as a test case?

**Comment by panzhongxian** [comment]
@mostafa I am new to Go. Can you give me some guidelines to add the test case? Just source file and line/function is OK. I can learn by reading the code.

**Comment by mostafa** [comment]
You can read this one, as it's directly related to breakpoints and pretty straight-forward:
https://github.com/mostafa/goja/blob/debugger/debugger_test.go#L9

**Comment by mostafa** [comment]
Use this naming convention when appropriate:
https://github.com/mostafa/goja/blob/debugger/debugger_test.go#L322

**Comment by mostafa** [comment]
Since #10 is merged, I'll close this. Feel free to open it whenever needed.
